### ISSUE TITLE
How i can compare 2 vectors?

### ISSUE THREAD

**Issue by i7p9h9** [RaviSoji/plda#46]
In previous version you have a discriminator, which can compare 2 instance, and make decision is it the same or different classes. Now the discriminator is removed, why? Can you provide any example how i can compare 2 vectors?

**Comment by RaviSoji** [comment]
I removed the discriminator because it seemed out of scope for the PLDA repository.

More important, to make the discriminator work, I had hardcoded prior probabilities specific to the problem that I was working on at that time (making the implementation not very generalizable) and performed quite a few hacks (making the discriminator more opaque).

If you would like to implement the discriminator, I would suggest taking a look at equation (5) in the Ioffe (2006) paper and using the marginal likelihood function I implemented because equation (6) in the paper looks incorrect.

**Comment by RaviSoji** [comment]
I'm closing this issue for now. Feel free to get in touch if you need further help!
