### ISSUE TITLE
Some minor mistake In "classifier.model.calc_same_diff_likelihood_ratio(U_model_p, U_model_g)" 

### ISSUE THREAD

**Issue by vishalgoyal316** [RaviSoji/plda#53]
### Expected Behavior
classifier.model.calc_same_diff_likelihood_ratio(U_model_p, U_model_g)
in this function the snippet should be  "U_model_same = np.concatenate( 
[U_model_p], [U_model_g])"

### Actual Behavior
 U_model_same = np.concatenate([ U_model_p, U_model_g,])

### Steps to Reproduce the Behavior

Only two brackets are missing.

**Comment by seandickert** [comment]
Hi, if possible, could you provide some simplified sample inputs that are causing the error as well as the numpy version you have installed.

As is, using numpy version >= 1.14, as suggested in the environment.yml, would throw an error if run by passing 2 separate lists, rather than a list of lists (see https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.concatenate.html).

**Comment by RaviSoji** [comment]
Thanks for raising this point, and I apologize for taking so long to reply to this.

I am actually not clear on what the error is if the data are supplied the way the function expects them to be supplied. I agree that some examples would be helpful. At the moment, my impression is that this issue is more about a preference for what the expected data structure ought to be, but let me know if I am misunderstanding.

I've set aside time tomorrow to update the demo to include an example and address the pull request, but if you can give more information, maybe I can address this by end of day tomorrow. I'm making a note to self to check this again a week from now, but if there's no response by then, I will close this issue.

Thanks again,
Ravi B. Sojitra
