### ISSUE TITLE
error:"array must not contain infs or NaNs"

### ISSUE THREAD

**Issue by Xixo99** [RaviSoji/plda#57]
error:"array must not contain infs or NaNs"
![image](https://user-images.githubusercontent.com/52273490/115491634-e4a6e580-a292-11eb-9eba-adfd8a2540e8.png)
![image](https://user-images.githubusercontent.com/52273490/115491719-115afd00-a293-11eb-8d0b-11c9ed5fb94d.png)
![image](https://user-images.githubusercontent.com/52273490/115491922-6c8cef80-a293-11eb-8c01-846833c2e62d.png)

When I use this framework for PLDA experiments, this error often appears. I can guarantee that all my input data are obtained through preprocessing, and they are all positive finite numbers, and the data scale is not large.
I don't know why such errors occur. Do you have any additional requirements for the input data?

**Comment by RaviSoji** [comment]
Do you still have this issue when you reduce the number of principal components to 2? If so, could you run PCA on it and report back the 5-10 largest eigenvalues?

Also, if you have more than 30 observations, I would use all of them for diagnostic purposes to see whether the issue is that you don't have much variance in the input variables/features. I never fit this model on datasets with less than 300-400 observations.

Just a heads up that I may not be too much help in the short term -- trying to meet a few deadlines this week 😅.

**Comment by RaviSoji** [comment]
It's been two weeks without a reply, so I am assuming you figured it out. If not, let me know, and we can keep going back and forth!

Thanks for taking the time to ask about this!
Ravi B. Sojitra
